
package GUI;

import GUI.contoller.SaveController;

public class ArmorTabPanel extends javax.swing.JPanel {

    private boolean compare;
    
    private Model model;
    
    /**
     * Creates new form ArmorTabPanel
     */
    public ArmorTabPanel()
    {
        initComponents();
        compare = true;
    }
    
    public void setModel(Model m)
    {
        armorCreationPanelUpper.setModel(m);
        armorCreationPanelLower.setModel(m);
        model = m;
        model.setColorCompareArmor(compare);
    }

    public void setPanelIDNumber(int id)
    {
        armorCreationPanelUpper.setPanelIDNumber(id);
        armorCreationPanelLower.setPanelIDNumber(id + 1);
    }
    
    public void enableAllSubparts(boolean enable)
    {
        compareToggleButton.setEnabled(enable);
        
        armorCreationPanelLower.enableAllSubparts(enable);
        armorCreationPanelUpper.enableAllSubparts(enable);
    }
    
    public void setSaveController(SaveController sc)
    {
        armorCreationPanelLower.setSaveController(sc);
        armorCreationPanelUpper.setSaveController(sc);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        armorCreationPanelUpper = new GUI.ArmorCreationPanel();
        armorCreationPanelLower = new GUI.ArmorCreationPanel();
        compareToggleButton = new javax.swing.JToggleButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        compareToggleButton.setSelected(true);
        compareToggleButton.setText("Compare");
        compareToggleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                compareToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(armorCreationPanelUpper, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                    .addComponent(armorCreationPanelLower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(compareToggleButton)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(armorCreationPanelUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compareToggleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(armorCreationPanelLower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void compareToggleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_compareToggleButtonActionPerformed
    {//GEN-HEADEREND:event_compareToggleButtonActionPerformed
        // TODO add your handling code here:
        compare = !compare;
        model.setColorCompareArmor(compare);
        System.out.println("Compare " + compare);
    }//GEN-LAST:event_compareToggleButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.ArmorCreationPanel armorCreationPanelLower;
    private GUI.ArmorCreationPanel armorCreationPanelUpper;
    private javax.swing.JToggleButton compareToggleButton;
    // End of variables declaration//GEN-END:variables
}
