package GUI;

import GUI.contoller.SaveController;
import GUI.popups.SavePresetPopupFrame;

public class ArmorCreationPanel extends javax.swing.JPanel {

    private SaveController saveController;
    
    /**
     * Creates new form ArmorCreationPanel
     */
    public ArmorCreationPanel()
    {
        initComponents();
    }

    public void setModel(Model m)
    {
        armorComponentSelectionPanel.setModel(m);
        armorStatsPanel.setModel(m);
    }

    public void setPanelIDNumber(int id)
    {
        armorComponentSelectionPanel.setPanelIDNumber(id);
        armorStatsPanel.setPanelIDNumber(id);
    }
    
    public void enableAllSubparts(boolean enable)
    {
        fullPreviewButton.setEnabled(enable);
        saveButton.setEnabled(enable);
        armorStatsPanel.setEnabled(enable);
        armorComponentSelectionPanel.setEnabled(enable);
        
        armorComponentSelectionPanel.enableAllSubparts(enable);
    }
    
    public void setSaveController(SaveController sc)
    {
        saveController = sc;
    }
    
    private void saveArmorPreset()
    {
        SavePresetPopupFrame save = new SavePresetPopupFrame();
        save.setLocation(100, 100);
        save.setSaveController(saveController);
        
        save.sendItemData(armorComponentSelectionPanel.getArmorSaveData());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        armorComponentSelectionPanel = new GUI.ArmorComponentSelectionPanel();
        fullPreviewButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        armorStatsPanel = new GUI.ArmorStatsPanel();
        loadSavedLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fullPreviewButton.setText("Full Preview");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveButtonActionPerformed(evt);
            }
        });

        loadSavedLabel.setText("Load Saved :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadSavedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(armorComponentSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(armorStatsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullPreviewButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(fullPreviewButton)
                    .addComponent(loadSavedLabel)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(armorComponentSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(armorStatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveButtonActionPerformed
    {//GEN-HEADEREND:event_saveButtonActionPerformed
        // TODO add your handling code here:
        saveArmorPreset();
    }//GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.ArmorComponentSelectionPanel armorComponentSelectionPanel;
    private GUI.ArmorStatsPanel armorStatsPanel;
    private javax.swing.JButton fullPreviewButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel loadSavedLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
