package GUI;

import GUI.contoller.SaveController;
import GUI.popups.SavePresetPopupFrame;

/**
 * Holds a WeaponComponentSelectionPanel and a WeaponStatsPanel. Also holds a
 * Save Button, Saved Weapon Combo Box and a FullPreview Button.
 */
public class WeaponCreationPanel extends javax.swing.JPanel {

    private SaveController saveController;
    
    /**
     * The number used to refer to which weapon set this panel makes changes to.
     * Also, links this panel to the appropriate WeaponStatsPanel
     */
    private int panelIDNumber;
    
    /**
     * The pointer to the Model that the program will use. Is initialized in
     * BLGCMainFrame.java
     */
    private Model model;
    
    /**
     * Creates new form WeaponCreationPanel
     */
    public WeaponCreationPanel()
    {
        initComponents();
    }

    /**
     * Sets the panelIDNumber for the WeaponComponentSelectionPanel in this
     * WeaponCreationPanel.
     *
     * @param idNum The ID number that will be assigned.
     */
    public void setPanelIDNumberAndPrimacy(int idNum, boolean primary)
    {
        weaponStatsDisplayPanel.setPanelIDNumberAndPrimacy(idNum, primary);
        weaponComponentSelectionPanel.setPanelIDNumberAndPrimacy(idNum, primary);
        panelIDNumber = idNum;
    }

    /**
     * @param m The model
     */
    public void setModel(Model m)
    {
        weaponStatsDisplayPanel.setModel(m);
        weaponComponentSelectionPanel.setModel(m);
        model = m;
    }
    
    public void setSaveController(SaveController sc)
    {
        saveController = sc;
    }
    
    public void enableAllSubparts(boolean enable)
    {
        fullPreviewButton.setEnabled(enable);
        loadSavedLabel.setEnabled(enable);
        saveButton.setEnabled(enable);
        savedItemComboBox.setEnabled(enable);
        weaponStatsDisplayPanel.setEnabled(enable);
        weaponComponentSelectionPanel.setEnabled(enable);
        
        weaponStatsDisplayPanel.enableAllSubparts(enable);
        weaponComponentSelectionPanel.enableAllSubparts(enable);
    }
    
    private void saveWeaponPreset()
    {
        SavePresetPopupFrame save = new SavePresetPopupFrame();
        save.setLocation(100, 100);
        save.setSaveController(saveController);
        
        save.sendItemData(weaponComponentSelectionPanel.getWeaponSaveData());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        saveButton = new javax.swing.JButton();
        fullPreviewButton = new javax.swing.JButton();
        weaponComponentSelectionPanel = new GUI.WeaponComponentSelectionPanel();
        weaponStatsDisplayPanel = new GUI.WeaponStatsPanel();
        loadSavedLabel = new javax.swing.JLabel();
        savedItemComboBox = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveButtonActionPerformed(evt);
            }
        });

        fullPreviewButton.setText("Full Preview");
        fullPreviewButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fullPreviewButtonActionPerformed(evt);
            }
        });

        weaponComponentSelectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Components", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, null, java.awt.Color.black));
        weaponComponentSelectionPanel.setToolTipText("");

        weaponStatsDisplayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Stats", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        loadSavedLabel.setText("Load Saved :");

        savedItemComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadSavedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savedItemComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(weaponComponentSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weaponStatsDisplayPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullPreviewButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(fullPreviewButton)
                    .addComponent(loadSavedLabel)
                    .addComponent(savedItemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weaponComponentSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(weaponStatsDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fullPreviewButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fullPreviewButtonActionPerformed
    {//GEN-HEADEREND:event_fullPreviewButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(model.getWeapon(panelIDNumber).toString());
    }//GEN-LAST:event_fullPreviewButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveButtonActionPerformed
    {//GEN-HEADEREND:event_saveButtonActionPerformed
        // TODO add your handling code here:
        saveWeaponPreset();
    }//GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fullPreviewButton;
    private javax.swing.JLabel loadSavedLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox savedItemComboBox;
    private GUI.WeaponComponentSelectionPanel weaponComponentSelectionPanel;
    private GUI.WeaponStatsPanel weaponStatsDisplayPanel;
    // End of variables declaration//GEN-END:variables
}
