
package GUI.popups;

import GUI.contoller.SaveController;
import java.awt.Color;

public class SavePresetPopupFrame extends javax.swing.JFrame {
    
    private String itemData = "";
    
    boolean clearSaveName = false;
    
    private SaveController saveController;
    
    /**
     * Creates new form SavePresetPopupFrame
     */
    public SavePresetPopupFrame()
    {
        initComponents();
        this.setVisible(true);
        this.setAlwaysOnTop(true);
    }
    
    public void setSaveController(SaveController sc)
    {
        saveController = sc;
        saveController.setEnableMainFrame(false);
    }
    
    public void sendItemData(String data)
    {
        itemData = data;
    }
    
    private void save()
    {
        if (enterNameTextField.getText().trim().equals(""))
        {
            enterNameTextField.setBackground(Color.PINK);
            enterNameTextField.setText("Name cannot be blank.");
            clearSaveName = true;
        }
        else if (enterNameTextField.getText().contains(","))
        {
            enterNameTextField.setBackground(Color.PINK);
            enterNameTextField.setText("Commas not allowed.");
            clearSaveName = true;
        }
        else
        {
            saveAndClose();
        }
    }
    
    private void saveAndClose()
    {
        saveController.setEnableMainFrame(true);
        String saveString = enterNameTextField.getText().trim() + ", " + itemData;
        System.out.println(saveString);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        savePanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        enterNameLabel = new javax.swing.JLabel();
        enterNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
        });

        savePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveButtonActionPerformed(evt);
            }
        });

        enterNameLabel.setText("Enter name for weapon/armor set");

        enterNameTextField.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                enterNameTextFieldMouseClicked(evt);
            }
        });
        enterNameTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                enterNameTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout savePanelLayout = new javax.swing.GroupLayout(savePanel);
        savePanel.setLayout(savePanelLayout);
        savePanelLayout.setHorizontalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterNameLabel)
                    .addComponent(enterNameTextField)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        savePanelLayout.setVerticalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveButtonActionPerformed
    {//GEN-HEADEREND:event_saveButtonActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void enterNameTextFieldMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_enterNameTextFieldMouseClicked
    {//GEN-HEADEREND:event_enterNameTextFieldMouseClicked
        // TODO add your handling code here:
        if (clearSaveName) {
            enterNameTextField.setText("");
            enterNameTextField.setBackground(Color.WHITE);
            clearSaveName = false;
        }
    }//GEN-LAST:event_enterNameTextFieldMouseClicked

    private void enterNameTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_enterNameTextFieldKeyReleased
    {//GEN-HEADEREND:event_enterNameTextFieldKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            save();
        }
    }//GEN-LAST:event_enterNameTextFieldKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        // TODO add your handling code here:
        saveController.setEnableMainFrame(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SavePresetPopupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SavePresetPopupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SavePresetPopupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SavePresetPopupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new SavePresetPopupFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterNameLabel;
    private javax.swing.JTextField enterNameTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel savePanel;
    // End of variables declaration//GEN-END:variables
}
